version: "3"
services:

  memgraph:
    image: memgraph/memgraph:2.19.0
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    networks:
      - llm_agent_network
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_log:/var/log/memgraph
      - memgraph_etc:/etc/memgraph

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: llm_nginx
    env_file:
      - ../backend/.env
    restart: unless-stopped

    ports:
      - "1980:80"    # http
      - "1981:443"   # https
    volumes:
      - ../frontend:/var/www/html/web
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    networks:
      - llm_agent_network

  web:
    container_name: llm_agent
    build: ../backend
    image: lazy-rabbit-agent
    command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - llm_agent_network

  celery_worker:
    container_name: celery_worker
    build: ../backend
    image: lazy-rabbit-agent
    command: ["sh", "-c", "celery -A worker.celery_app worker -B -l info"]
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env
    depends_on:
      - web
    networks:
      - llm_agent_network

  db:
    container_name: mariadb
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/password.txt:/run/secrets/db-password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"
    # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:8080"
volumes:
  db-data:
      driver: local
  memgraph_data:
    driver: local
  memgraph_log:
    driver: local
  memgraph_etc:
    driver: local
    
networks:
  llm_agent_network:
    driver: bridge
