
services:

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: llm_nginx
    restart: unless-stopped

    ports:
      - "1980:80"    # http
      - "1981:443"   # https
    volumes:
      - ../frontend/dist:/var/www/html/web
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    networks:
      - lazy_rabbit_network

  web:
    container_name: llm_agent
    build: ../backend
    image: lazy-rabbit-agent
    command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - lazy_rabbit_network

  celery_worker:
    container_name: celery_worker
    build: ../backend
    image: lazy-rabbit-agent
    command: ["sh", "-c", "celery -A worker.celery_app worker -B -l info"]
    volumes:
      - ../backend:/app
    env_file:
      - ./.env
    depends_on:
      - web
    networks:
      - lazy_rabbit_network

  db:
    container_name: mariadb
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/password.txt:/run/secrets/db-password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - lazy_rabbit_network
  adminer:
    # default port 8080
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:8080"
    networks:
      - lazy_rabbit_network
  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lazy_rabbit_network
volumes:
  db-data:
      driver: local

networks:
  lazy_rabbit_network:
    driver: bridge
