"""add user profile fields

Revision ID: 003
Revises: 002
Create Date: 2025-12-14 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('identity', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('temperature_sensitivity', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('activity_context', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('other_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'other_preferences')
    op.drop_column('users', 'activity_context')
    op.drop_column('users', 'temperature_sensitivity')
    op.drop_column('users', 'style')
    op.drop_column('users', 'identity')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###





